"""add batches tests attempts

Revision ID: 1ba0154d1e3c
Revises: 6b5ff24d60d0
Create Date: 2025-12-31 23:48:58.119389
"""
from __future__ import annotations
from alembic import op
import sqlalchemy as sa

revision = '1ba0154d1e3c'
down_revision = '6b5ff24d60d0'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'user_id', name='uq_batch_members_batch_user')
    )
    op.create_index(op.f('ix_batch_members_batch_id'), 'batch_members', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_members_user_id'), 'batch_members', ['user_id'], unique=False)
    op.create_unique_constraint('uq_questions_test_position', 'questions', ['test_id', 'position'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_questions_test_position', 'questions', type_='unique')
    op.drop_index(op.f('ix_batch_members_user_id'), table_name='batch_members')
    op.drop_index(op.f('ix_batch_members_batch_id'), table_name='batch_members')
    op.drop_table('batch_members')
    # ### end Alembic commands ###
