"""add refresh tokens

Revision ID: 49c59f4dd045
Revises: b2a984c868bd
Create Date: 2025-12-31 21:49:51.839767
"""
from __future__ import annotations

revision = '49c59f4dd045'
down_revision = 'b2a984c868bd'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
